Add a default app.yaml
jenkins-x/ext-jacoco pull request #78
Opened 2019-02-07 09:37 UTC by daveconde

The app should now appear in `kubectl get apps`

2019-02-07 16:41 UTC, hferentschik requested changes
I did not know about this file. Cool to add it. 

What's about sticking to https://www.conventionalcommits.org/en/v1.0.0-beta.3/ for writing commit messages? 

Also I am in favor of creating issues for each change. Not sure what you think about this?

2019-02-07 16:41 UTC, hferentschik commented on charts/jx-app-jacoco/templates/app.yaml
> +spec: {}
Let's add a newline to keep GitHub happy ;-)

2019-02-07 17:30 UTC, daveconde commented
> I did not know about this file. Cool to add it.
> 
> What's about sticking to https://www.conventionalcommits.org/en/v1.0.0-beta.3/ for writing commit messages?

I haven't seen that before. I'll try and stick with that :)

> 
> Also I am in favor of creating issues for each change. Not sure what you think about this?

Sure I'll open an issue for both PRs so they are tracked. 

Let's hold this one until Pete is back, I'd like to discuss this approach vs automatically adding an App resource if one doesn't exist.

2019-02-07 17:30 UTC, daveconde commented
/hold

2019-02-07 18:17 UTC, hferentschik commented
> I haven't seen that before. I'll try and stick with that :)

Thanks. It's a bit new to me as well. At least in this format. I am a strong believer in properly formatted commit messages, but we used a different format in the projects we worked on.

@pmuir mentioned conventional commits and that's fine with me. Especially since it also aids automated changelog generation.

> Sure I'll open an issue for both PRs so they are tracked.

+1 :-)

> Let's hold this one until Pete is back, I'd like to discuss this approach vs automatically adding an App resource if one doesn't exist.

Absolutely.

2019-02-11 10:17 UTC, pmuir commented
> this approach vs automatically adding an App resource if one doesn't exist.

Yes, we need to add an App resource automatically if one doesn't exist, and we also need to handle the case where the App adds more than one App resource (what does that mean?).

2019-02-11 10:17 UTC, pmuir commented
/approve

2019-02-11 10:46 UTC, hferentschik requested changes
Can we not squash that into a single commit with a proper commit message?

2019-02-11 11:36 UTC, daveconde commented
> Can we not squash that into a single commit with a proper commit message?

Looking better?

2019-02-11 12:30 UTC, hferentschik commented
/approve

2019-02-11 12:30 UTC, hferentschik approved these changes

2019-02-11 12:49 UTC, daveconde commented
/hold cancel

2019-02-11 12:50 UTC, merged